#!/usr/bin/env python3
"""
Alexandria Configuration Wizard
================================

Interactive setup script for Alexandria configuration.
Creates or updates the .env file in project root.

Usage:
    python scripts/configure.py           # Interactive wizard
    python scripts/configure.py --show    # Show current config
    python scripts/configure.py --test    # Test connections
"""

import os
import sys
import argparse
from pathlib import Path

# Find project root
SCRIPTS_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPTS_DIR.parent
ENV_FILE = PROJECT_ROOT / '.env'

# Default values
DEFAULTS = {
    'QDRANT_HOST': '192.168.0.151',
    'QDRANT_PORT': '6333',
    'QDRANT_COLLECTION': 'alexandria',
    'CALIBRE_LIBRARY_PATH': r'G:\My Drive\alexandria',
    'LOCAL_INGEST_PATH': str(Path.home() / 'Downloads'),
}


def load_existing_env() -> dict:
    """Load existing .env file if it exists."""
    config = {}
    if ENV_FILE.exists():
        with open(ENV_FILE, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    config[key.strip()] = value.strip().strip('"').strip("'")
    return config


def save_env(config: dict):
    """Save configuration to .env file."""
    lines = [
        "# Alexandria Configuration",
        "# Generated by configure.py",
        "#",
        "# Edit this file or run: python scripts/configure.py",
        "",
        "# Qdrant Vector Database",
        f"QDRANT_HOST={config.get('QDRANT_HOST', DEFAULTS['QDRANT_HOST'])}",
        f"QDRANT_PORT={config.get('QDRANT_PORT', DEFAULTS['QDRANT_PORT'])}",
        f"QDRANT_COLLECTION={config.get('QDRANT_COLLECTION', DEFAULTS['QDRANT_COLLECTION'])}",
        "",
        "# Calibre Library",
        f"CALIBRE_LIBRARY_PATH={config.get('CALIBRE_LIBRARY_PATH', DEFAULTS['CALIBRE_LIBRARY_PATH'])}",
        "",
        "# Local File Ingestion",
        f"LOCAL_INGEST_PATH={config.get('LOCAL_INGEST_PATH', DEFAULTS['LOCAL_INGEST_PATH'])}",
        "",
        "# OpenRouter API (optional - for CLI testing)",
        f"# OPENROUTER_API_KEY=sk-or-v1-...",
        "",
    ]

    with open(ENV_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"\nSaved to: {ENV_FILE}")


def prompt(message: str, default: str = '') -> str:
    """Prompt user for input with default value."""
    if default:
        user_input = input(f"{message} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        return input(f"{message}: ").strip()


def test_qdrant(host: str, port: str) -> bool:
    """Test Qdrant connection."""
    try:
        import requests
        url = f"http://{host}:{port}"
        response = requests.get(url, timeout=5)
        return response.status_code == 200
    except Exception as e:
        print(f"  Error: {e}")
        return False


def test_calibre(path: str) -> bool:
    """Test Calibre library path."""
    db_path = Path(path) / 'metadata.db'
    return db_path.exists()


def interactive_setup():
    """Run interactive configuration wizard."""
    print("\n" + "=" * 50)
    print("Alexandria Configuration Wizard")
    print("=" * 50)

    # Load existing config
    existing = load_existing_env()

    if existing:
        print(f"\nFound existing config: {ENV_FILE}")
        print("Press Enter to keep current values, or type new value.\n")
    else:
        print("\nNo existing config found. Setting up new configuration.\n")

    config = {}

    # Qdrant settings
    print("--- Qdrant Vector Database ---")
    config['QDRANT_HOST'] = prompt(
        "Qdrant host",
        existing.get('QDRANT_HOST', DEFAULTS['QDRANT_HOST'])
    )
    config['QDRANT_PORT'] = prompt(
        "Qdrant port",
        existing.get('QDRANT_PORT', DEFAULTS['QDRANT_PORT'])
    )
    config['QDRANT_COLLECTION'] = prompt(
        "Collection name",
        existing.get('QDRANT_COLLECTION', DEFAULTS['QDRANT_COLLECTION'])
    )

    # Test Qdrant
    print(f"\nTesting Qdrant connection... ", end='')
    if test_qdrant(config['QDRANT_HOST'], config['QDRANT_PORT']):
        print("OK")
    else:
        print("FAILED (server may be offline)")

    # Calibre settings
    print("\n--- Calibre Library ---")
    config['CALIBRE_LIBRARY_PATH'] = prompt(
        "Calibre library path",
        existing.get('CALIBRE_LIBRARY_PATH', DEFAULTS['CALIBRE_LIBRARY_PATH'])
    )

    # Test Calibre
    print(f"Checking Calibre database... ", end='')
    if test_calibre(config['CALIBRE_LIBRARY_PATH']):
        print("OK")
    else:
        print("NOT FOUND (check path)")

    # Local ingest path
    print("\n--- Local File Ingestion ---")
    config['LOCAL_INGEST_PATH'] = prompt(
        "Default directory for local files",
        existing.get('LOCAL_INGEST_PATH', DEFAULTS['LOCAL_INGEST_PATH'])
    )

    # Save
    print("\n" + "-" * 50)
    save = input("Save configuration? [Y/n]: ").strip().lower()
    if save != 'n':
        save_env(config)
        print("\nConfiguration complete!")
        print("Run 'python scripts/config.py' to verify.")
    else:
        print("\nConfiguration cancelled.")


def show_config():
    """Show current configuration."""
    # Import config to get resolved values
    sys.path.insert(0, str(SCRIPTS_DIR))
    from config import print_config
    print_config()


def test_connections():
    """Test all connections."""
    print("\nTesting Alexandria connections...\n")

    # Load config
    sys.path.insert(0, str(SCRIPTS_DIR))
    from config import QDRANT_HOST, QDRANT_PORT, CALIBRE_LIBRARY_PATH

    # Test Qdrant
    print(f"Qdrant ({QDRANT_HOST}:{QDRANT_PORT})... ", end='')
    if test_qdrant(QDRANT_HOST, str(QDRANT_PORT)):
        print("OK")
    else:
        print("FAILED")

    # Test Calibre
    print(f"Calibre ({CALIBRE_LIBRARY_PATH})... ", end='')
    if test_calibre(CALIBRE_LIBRARY_PATH):
        print("OK")
    else:
        print("FAILED")

    print()


def main():
    parser = argparse.ArgumentParser(
        description="Alexandria Configuration Wizard"
    )
    parser.add_argument('--show', action='store_true', help='Show current configuration')
    parser.add_argument('--test', action='store_true', help='Test connections')

    args = parser.parse_args()

    if args.show:
        show_config()
    elif args.test:
        test_connections()
    else:
        interactive_setup()


if __name__ == "__main__":
    main()
